version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-orders
    restart: unless-stopped
    ports:
      - "9595:80"
      - "6443:443"
    volumes:
      - ./:/usr/share/nginx/html
      - ./certs:/etc/nginx/ssl
      - ./Docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Docker/000-default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Docker/default-ssl.conf:/etc/nginx/conf.d/default-ssl.conf:ro
    depends_on:
      - php
      - db
    environment:
      - SERVER_NAME=orders.com.br
    networks:
      - ordens_net      

  php:  
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    restart: unless-stopped
    container_name: php-orders
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - SERVER_NAME=orders.com.br
    networks:
      - ordens_net

  db:
    container_name: orders_db
    image: mysql:8.0
    command: >
      mysqld --default-authentication-plugin=mysql_native_password 
             --character-set-server=utf8mb4 
             --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
      MYSQL_USER: system_user
      MYSQL_PASSWORD: system@2025!
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3318:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './Docker/my.cnf:/etc/mysql/conf.d/my.cnf'
      - ./Docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ordens_net

networks:
  ordens_net:
    driver: bridge

volumes:
  db_data:
